### ISSUE TITLE
Uncaught error if no authentication method present

### ISSUE THREAD

**Issue by lucaagostini** [lucaagostini/aws-es-auth-proxy#1]
If it's not present any authentication method the following error occour:

```
Traceback (most recent call last):
  File "env/bin/aws-es-auth-proxy", line 33, in <module>
    run()
  File "env/bin/aws-es-auth-proxy", line 28, in run
    logging.info("Loading AWS credentials from: " + config.aws_service_credentials.method)
AttributeError: 'NoneType' object has no attribute 'method
```

The error must be managed properly

**Comment by lucaagostini** [comment]
Fixed in 4e6c0a3f6aa97cbfc6d835e9801667206a231a7c
